### ISSUE TITLE
GitLab-CI在GitLab中的应用

### ISSUE THREAD

**Issue by ilvseyinfu** [ilvseyinfu/blog#8]
### 什么是持续化集成？ ###
> 持续化集成是一种软件开发实践，即团队开发成员经常集成他们的工作，通过每个成员每天至少集成一次，也就意味着每个成员每天至少会集成多次，每次集成通过自动化的构建(包括编译，发布，自动化测试)来验证，从而尽早的发现集成错误。
--来自[百度百科 ](https://baike.baidu.com/item/%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90/6250744?fr=aladdin)   

在我看来，持续化继承就是我们每天向我们的代码库push代码，或者merge request后，会自动触发gitlab-ci，也就是会自动发生持续化继承，包括合并代码，安装依赖，编译，测试，发布等一系列流程，我们可以看到代码是在持续化集成中哪一步失败，这样就可以针对性的解决问题，持续化集成原则之一是每次构建都可以生成可发布的产品，也就是说每一次构建都要100%的通过，一句话就是**早发现，早解决**，而持续化继承可以将繁琐的，重复的工作中抽离出来。   

gitlab-ci就是一套配合gitlab使用的持续化继承系统，当我们每一次push代码或者merge request后，会自动触发gitlab-ci

#### 先来看看一些在GitLab中的名词: ####    

Pipeline：
```
 一次pipeline相当于一次构建任务，里面包含了多个流程，如安装依赖，运行测试，编译，等
```    
Stages：
```yml
表示构建阶段，就是pipeline里面的流程，我们可以在一次pipeline中定义多个stages，   
所有的stages会按照顺序执行，也就说，只有当上一个stage成功完成后，下一个才会开始，   
如果失败，则后面不会运行，此次构建(pipeline)任务失败，只有当所有的stages都成功完成，   
此次pipeline构建任务才会成功
```
Jobs：
```yml
表示构建工作，指每一个Stage里执行的工作，可以在一个Stage里面定义多个Jobs，   
在同一个Stage里面Jobs是并发执行，只有当所有的Jobs都执行成功，该Stage才会成功，   
如果有一个Job失败，那么该Stage失败，则此次pipeline失败   

eg:   

job_name:
  script:
    - rake spec
    - coverage
  stage: test
  only:
    - master
  except:
    - develop
  tags:
    - ruby
    - postgres
  allow_failure: true
```   

Gitlab-Runner：
```
通俗点理解就是 上面的jobs，都是由谁来执行的 
```   
   
#### 接下来看看如何配置你的.gitlab-ci.yml: ####

[GitLab官网](https://git.hlj.team/help/ci/yaml/README)  具体用法以及参数详情你可以在这里获得

此文用来描述.gitlab-ci.yml的用法，.gitlab-ci.yml 是为了告诉gitlab-runner如何管理你的项目工作

从7.12版本开始，gitlab-ci使用YAML文件来配置项目，gitlab-ci文件放置在你项目的根目录，包含了一些解释你的项目如何去构建

YAML文件定义了一系列工作(包含限制，比如什么时候运行)，这些jobs需要被命名并且定义为顶级元素，通常必须包含至少一项scripts   

#### 最后，我们给出一个示例: ####

```yml
stages:
  - install_deps
  - test
  - build
  - deploy_test
  - deploy_production

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/


# 安装依赖
install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - npm install


# 运行测试用例
test:
  stage: test
  only:
    - develop
    - master
  script:
    - npm run test


# 编译
build:
  stage: build
  only:
    - develop
    - master
  script:
    - npm run clean
    - npm run build:client
    - npm run build:server


# 部署测试服务器
deploy_test:
  stage: deploy_test
  only:
    - develop
  script:
    - pm2 delete app || true
    - pm2 start app.js --name app


# 部署生产服务器
deploy_production:
  stage: deploy_production
  only:
    - master
  script:
    - bash scripts/deploy/deploy.sh
```
